apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-activity-deploymentww
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-activity-serviceww
  template:
    metadata:
      labels:
        app: user-activity-serviceww
    spec:
      containers:
      - name: user-activity-serviceww
        image: sachinitenn/github_user_activity_service:github_user_activity_service
        command: ["python", "github_user_activity_service/github_user_activity_service.py"]
        command: ["ls","github_user_activity_service"]
---
apiVersion: v1
kind: Service
metadata:
  name: user-activity-serviceww
spec:
  selector:
    app: user-activity-serviceww
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer
